### ISSUE TITLE
GroupOutgoingCallingPlanOriginatingGetListRequest

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#16]
Hi
Can you double check that you are able to read the departmentName and permissions within GroupOutgoingCallingPlanOriginatingGetListRequest
when i try and do 
$response->getDepartmentPermissions()->getdepartmentName()
getting
PHP Fatal error:  Uncaught Error: Call to a member function getdepartmentName() on array in

thanks
array(1) {
  [0]=>
  object(CWM\BroadWorksConnector\Ocip\Models\OutgoingCallingPlanOriginatingDepartmentPermissions)#23 (3) {
    ["departmentKey":"CWM\BroadWorksConnector\Ocip\Models\OutgoingCallingPlanOriginatingDepartmentPermissions":private]=>
    object(CWM\BroadWorksConnector\Ocip\Models\EnterpriseDepartmentKey)#24 (2) {
      ["serviceProviderId":"CWM\BroadWorksConnector\Ocip\Models\EnterpriseDepartmentKey":private]=>
      string(21) "serviceProviderId"
      ["name":"CWM\BroadWorksConnector\Ocip\Models\EnterpriseDepartmentKey":private]=>
      string(15) "name"
    }
    ["departmentName":"CWM\BroadWorksConnector\Ocip\Models\OutgoingCallingPlanOriginatingDepartmentPermissions":private]=>
    string(15) "Test Enterprise"
    ["permissions":"CWM\BroadWorksConnector\Ocip\Models\OutgoingCallingPlanOriginatingDepartmentPermissions":private]=>
    object(CWM\BroadWorksConnector\Ocip\Models\OutgoingCallingPlanOriginatingPermissions)#29 (14) {
      ["group":"CWM\BroadWorksConnector\Ocip\Models\OutgoingCallingPlanOriginatingPermissions":private]=>
      string(5) "Allow"
      ["

**Comment by cwmiller** [comment]
`getDepartmentPermissions()` returns an array of `OutgoingCallingPlanOriginatingDepartmentPermissions`, one for each department in the group.
