### ISSUE TITLE
 Uncaught TypeError: Argument 1 passed to CWM\BroadWorksConnector\Ocip\Models\UserServiceIsAssignedRequest::setServiceName()

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#18]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CWM\BroadWorksConnector\Ocip\Models\UserServiceIsAssignedRequest::setServiceName() must be an instance of CWM\BroadWorksConnector\Ocip\Models\UserService, string given, called in 
 and defined in /vendor/cwm/broadworks-connector/src/Ocip/Models/UserServiceIsAssignedRequest.php:73
is this correct? same with GroupServiceIsAssignedRequest
    public function setServiceName(_**\CWM\BroadWorksConnector\Ocip\Models\UserService**_ $serviceName)
    {
        $this->serviceName = $serviceName;
        return $this;
    }

**Comment by TwinMist** [comment]
Any update on this as looks like it is in a lot of the code,

**Comment by TwinMist** [comment]
many thanks, how do you install stable release with composer?

**Comment by cwmiller** [comment]
`composer require cwm/broadworks-connector:^2`

**Comment by TwinMist** [comment]
Many thanks, now working using the stable release
