### ISSUE TITLE
Uncaught Error: Class 'OcipClient' not found in 

### ISSUE THREAD

**Issue by andyrav** [cwmiller/broadworks-connector#2]
Hi
i am getting the following error:
Fatal error: Uncaught Error: Class 'OcipClient' not found in 
i have install the composer
and my files starts wilth
<?php
include_once 'vendor/autoload.php';
include_once 'src/OcipClient.php';
$ocip = new OcipClient(URL, OCI_USER, OCI_PASS);

What am i doing wrong iam i missing a use xxx ?

many thanks

**Comment by cwmiller** [comment]
Sorry, the example provided in the readme didn't include the namespace imports. I've updated the readme to include a more complete example.
