### ISSUE TITLE
Stop fatal eror

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#22]
Hi.
Is there away for it not to throw a fatal error, which cause a script to exit, where there is a error in the code

PHP Fatal error:  Uncaught CWM\BroadWorksConnector\Ocip\BadResponseException: Response doesn't begin with a BroadsoftDocument element. 

thanks

**Comment by TwinMist** [comment]
Hi. is threre any update on how to stop fatal errors. if you run the code again it works fine.
thanks

**Comment by cwmiller** [comment]
I tried it out for myself doing several requests in a row via TCP and also had the `BadResponseException` thrown. I'm still looking into exactly what is going on. It happened to me after the same amount of requests each time, and what triggered it was a newline before the XML in the response from the server. I'm not sure yet if this is a quirk with BroadWorks or just an issue with `TCPTransport`.

**Comment by cwmiller** [comment]
I think I've fixed this. Upgrade to version 2.1.2.

**Comment by TwinMist** [comment]
Spot on. Not crashing now. Nice work :-)
