### ISSUE TITLE
TimeOut Value

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#23]
Hi, Is there  any timeout value you can set when doing lots of queries?  i am getting a lot of PHP Fatal error: Not found etc, but if i run it again it returns a value

thanks

**Comment by cwmiller** [comment]
If you're using SOAP, you can adjust the `SoapClient` options (including timeout) by using the new `$options` argument to `OcipClient`. According to the documentation, you may also need to increase the value of system setting [default_socket_timeout](http://php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout).

So something along the lines of:

```php
init_set('default_socket_timeout', 3600);

$options = (new Options())
    ->setSoapClientOptions([
        'connection_timeout' => 3600
    ]);

$ocipClient = new OcipClient($url, $username, $password, $options)
```

**Comment by TwinMist** [comment]
No using tcp

**Comment by cwmiller** [comment]
If using TCP, then I believe the only thing you need to do is set `default_socket_timeout` like in my example above. Set the 2nd argument to amount of seconds you want as the timeout.
