### ISSUE TITLE
secure connection on port 2209

### ISSUE THREAD

**Issue by xciser77** [cwmiller/broadworks-connector#24]
i am trying to use the secure port 2209 on the server but I cannot get a connection
is this possible with the package ?

And if so what do we need to change

**Comment by cwmiller** [comment]
At this time it does not support SSL over TCP. I actually didn't know BroadWorks supported that! :)

**Comment by cwmiller** [comment]
Version 2.2.0 includes support for SSL/TLS connections. To use it, specify `tls` as the scheme in the connection URL e.g. `new OcipClient('tls://host.com:2209', 'username', 'password');`. Schemes `ssl`, `sslv2`, and `sslv3` can also be used if targeting an older system with older SSL versions.
