### ISSUE TITLE
UserCallForwardingSelectiveAddCriteriaRequest

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#27]
Hi
Can you double check you are not missing out holidaySchedule from UserCallForwardingSelectiveAddCriteriaRequest

XML is
<userId> UserId </userId>
<criteriaName> CriteriaName </criteriaName>
<timeSchedule> TimeSchedule </timeSchedule>
<holidaySchedule> HolidaySchedule </holidaySchedule>
<forwardToNumberSelection> CallForwardingSelectiveNumberSelection16 </forwardToNumberSelection>
<forwardToPhoneNumber> OutgoingDNorSIPURI </forwardToPhoneNumber>
<fromDnCriteria> CriteriaFromDn </fromDnCriteria> 

but you only have setTimeSchedule in the code

thanks

**Comment by cwmiller** [comment]
`UserCallForwardingSelectiveAddCriteriaRequest16` has it.
