### ISSUE TITLE
cannot connect after upgrade

### ISSUE THREAD

**Issue by xciser77** [cwmiller/broadworks-connector#28]
I upgrade from 2.1 to 2.2, but now my script doesn't connect anymore.
I made a copy of the 2.1, and when I switch back to 2.1 the script does connect

I don't get any error, the spinner from the browser keeps spinning thats is.

**Comment by cwmiller** [comment]
Yeah, I botched something in 2.2.0. I released 2.2.1 last night which should fix it.

**Comment by xciser77** [comment]
upgrade to 2.2.1 and it is indeed fixed, thanx
