### ISSUE TITLE
Add and modify

### ISSUE THREAD

**Issue by andyrav** [cwmiller/broadworks-connector#3]
Do you have any add and modify examples?
Thanks

**Comment by cwmiller** [comment]
The flow would be similar to the retrieval example. All commands to the OCI-P API are Request objects that get replied to with a Response object. Most add/modify commands will result in `SuccessResponse` or `ErrorResponse`.  To create a group, for example, you'd use an instance of `GroupAddRequest` which can result in a `SuccessResponse` or `ErrorResponse`.
