### ISSUE TITLE
Add user with no accessDeviceEndpoint

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#38]
Hi
is it possible you can you show me how to add a user with no device.
when i leave out setaccessDeviceEndpoint i get...
Choice not made between accessDeviceEndpoint, trunkAddressing on CWM\BroadWorksConnector\Ocip\Models\UserAddRequest17sp4.

but not sure how to set this to none.
you should be able just to leave it blank looking at BW logs xml
<command xsi:type="UserModifyRequest17sp4" echo="D32B34A4C6dsgfsdfsdfsdfDEA25F55" xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <userId>XXXX@XXXX.com</userId>
    <endpoint xsi:nil="true"/>
  </command>
thanks

**Comment by cwmiller** [comment]
See #37 
This should now be fixed in 3.0.3

**Comment by TwinMist** [comment]
Spot on many thanks now working
