### ISSUE TITLE
[Error 6004] OCI XML Request validation error

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#39]
hi
when trying to assign a user service iam getting
[Error 6004] OCI XML Request validation error
$serviceName = array('VOICE_MESSAGING_USER');
$request = (new UserServiceAssignListRequest())
	->setuserId($userId)
	->setserviceName(UserService::$serviceName);

any idea where iam going wrong?
this sort of worked but only for one service in the array
->setserviceName(array(UserService::$serviceName()))

thanks

**Comment by TwinMist** [comment]
sorted 
->setserviceName(array(UserService::$serviceName()))

**Comment by TwinMist** [comment]
->setserviceName(array(UserService::$serviceName()))
does not work when you have more than 1 value in the array
get the msg:  Uncaught Error: Function name must be a string in
any ideas

thanks

**Comment by cwmiller** [comment]
```php
$serviceName = array(UserService::VOICE_MESSAGING_USER());
$request = (new UserServiceAssignListRequest())
->setUserId($userId)
->setServiceName($serviceName);

**Comment by TwinMist** [comment]
what about if you wanted to assign more that 1 service within the same request?

**Comment by cwmiller** [comment]
Just add them to the array:
```php
$serviceName = array(
  UserService::VOICE_MESSAGING_USER(),
  UserService::VOICE_MESSAGING_USER_VIDEO(),
  UserService::THREE_WAY_CALL()
);

**Comment by fastcloudza** [comment]
Hi, I get the same error when I try to add a mobileIdentity using UserBroadWorksMobilityModifyRequest21. 
$request1 = (new UserBroadWorksMobilityModifyRequest21())
    ->setUserId($userId)
    ->setMobileIdentity($mobileIdentity);
$mobileIdentity = array('0731234567');
Thanks
