### ISSUE TITLE
colHeading

### ISSUE THREAD

**Issue by andyrav** [cwmiller/broadworks-connector#4]
Hi
Is it possible to add the option to use the colHeading (element name) for the array key?
echo $row->getCol()[0] . PHP_EOL;
change to
echo $row->getCol()['User Id'] . PHP_EOL;

will make it easyer to pull out data base on schema element name

thanks

**Comment by cwmiller** [comment]
Since all data objects are one-to-one representations of the BroadWork's OCI-P schema, I'd rather not modify them to include additional functionality.

If you'd like to use the column headings as an array key, then this can be achieved within your own code using `array_combine`:

```php
foreach ($response->getUserTable()->getRow() as $row) {
    $row = array_combine($response->getUserTable()->getColHeading(), $row->getCol());
    echo $row['User Id'] . PHP_EOL;
}
```

**Comment by andyrav** [comment]
hi
when i try 
$row = array_combine($response->getserviceProviderAdminTable()->getColHeading(), $row->getCol());
getting the error
PHP Fatal error:  Uncaught Error: Call to undefined method CWM\BroadWorksConnector\Ocip\Models\ServiceProviderAdminGetPolicyResponse20::getserviceProviderAdminTable()

any ideas why?
thanks
