### ISSUE TITLE
GroupCallCenterAddAgentListRequest

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#40]
Hi
Not sure if it is my request but when using below getting Multiple options selected between agentUserId, agentSkillList

$request = (new GroupCallCenterAddAgentListRequest())
		->setserviceUserId($serviceUserId)
		->setagentUserId($userIdList);

Multiple options selected between agentUserId, agentSkillList on CWM\BroadWorksConnector\Ocip\Models\GroupCallCenterAddAgentListRequest.string(136) "Multiple options selected between agentUserId, agentSkillList on CWM\BroadWorksConnector\Ocip\Models\GroupCallCenterAddAgentListRequest.

["agentSkillList":"CWM\BroadWorksConnector\Ocip\Models\GroupCallCenterAddAgentListRequest":private]=> array(0) { } } 

it is a choice so should be able to just use either?

many thanks

**Comment by cwmiller** [comment]
Looks like it's an issue with the validator when choices contain array elements. I'm working on a fix.

**Comment by cwmiller** [comment]
This should be fixed with version 3.0.4
