### ISSUE TITLE
Enhancement : OCI XML Request validation error

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#43]
Hi
Be great if there was a error in the validation that it could point out where the error was.

thanks

**Comment by cwmiller** [comment]
"OCI XML Request validation error" is the server-side message when a request fails validation. Unfortunately, it doesn't include any details of what caused it. The validator in the library tries to prevent this by validating the request before it goes to the server, however right now it only checks for required fields. There are other field requirements such as length that aren't yet being checked by the built-in validator.
