### ISSUE TITLE
UserSharedCallAppearanceDeleteEndpointListRequest14

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#48]
Hi
Could you tell me what is wrong with the following request
using
        "cwm/broadworks-connector": "dev-master",

$request = (new UserSharedCallAppearanceDeleteEndpointListRequest14())
		->setuserId($userId)
		->setaccessDeviceEndpoint(
			(new AccessDeviceEndpointKey())
				->setLinePort($linePort)
				->setAccessDevice(
				(new AccessDevice())
					->setDeviceLevel(AccessDeviceLevel::GROUP())
					->setDeviceName($deviceName)
			));

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CWM\BroadWorksConnector\Ocip\Models\UserSharedCallAppearanceDeleteEndpointListRequest14::setAccessDeviceEndpoint() must be of the type array, object given, 

if i remove <array> from UserSharedCallAppearanceDeleteEndpointListRequest14

public function setAccessDeviceEndpoint(array $accessDeviceEndpoint)
    {
        $this->accessDeviceEndpoint = $accessDeviceEndpoint;
        return $this;
    it works
thanks

**Comment by TwinMist** [comment]
Hi, can you help me on this query? 
Many thanks

**Comment by cwmiller** [comment]
`setAccessDeviceEndpoint` expects an array of `AccessDeviceEndpointKey`. Use:

```php
$request = (new UserSharedCallAppearanceDeleteEndpointListRequest14())
    ->setUserId($userId)
    ->setAccessDeviceEndpoint([
        (new AccessDeviceEndpointKey())
            ->setLinePort($linePort)
            ->setAccessDevice(
                (new AccessDevice())
                    ->setDeviceLevel(AccessDeviceLevel::GROUP())
                    ->setDeviceName($deviceName)
            )]);
```

**Comment by TwinMist** [comment]
Hi
Can you test the above for me as still getting the unexpected 'array' (T_ARRAY), expecting '('
error
cheers
