### ISSUE TITLE
ModifyRequest Response

### ISSUE THREAD

**Issue by andyrav** [cwmiller/broadworks-connector#6]
Hi 
What is the best way to hand the responce for example a  UserModifyRequest17sp4 as there is no response object that i can see?

ie like ...
if ($response instanceof SuccessResponse) {
echo "Success: ".$response . PHP_EOL;
} else if ($response instanceof ErrorResponse) {
echo "Error: ".$response->getSummary() . PHP_EOL;
exit();
}

many thanks

**Comment by andyrav** [comment]
ie.
if ($response instanceof SuccessResponse) {
	echo "Success: ".$response . PHP_EOL;
} else if ($response instanceof ErrorResponse) {
    echo "Error: ".$response->getSummary() . PHP_EOL;
    exit();
}

**Comment by cwmiller** [comment]
` UserModifyRequest17sp4` will only return `SuccessResponse` or `ErrorResponse`. `SuccessResponse` does not contain any data, but if it is returned then you know your request was completed successfully.

**Comment by andyrav** [comment]
What is the best  way in php write this please?

**Comment by cwmiller** [comment]
Basically, it's what you already pasted.

```php
if ($response instanceof SuccessResponse) {
    // Request was successful. Do whatever you need to do on success
} else {
    // Do something in case of an error, like just echoing the error message:
    echo 'Error: ' . $response->getSummary() . PHP_EOL;
}
