### ISSUE TITLE
Can't call static method VoiceMessagingMessageProcessing::UNIFIED_VOICE_AND_EMAIL_MESSAGING()

### ISSUE THREAD

**Issue by goodeys** [cwmiller/broadworks-connector#60]
This method cannot be called due to its definition been broken over two lines in the annotation

**Comment by cwmiller** [comment]
Thanks for reporting this. It is now fixed in release 3.1.3.

**Comment by goodeys** [comment]
No problem, loving your library.  Making my job a lot easier since I discovered it.
