### ISSUE TITLE
Retrieving Custom Media Files

### ISSUE THREAD

**Issue by TwinMist** [cwmiller/broadworks-connector#61]
Hi
Is it possible to Retrieving Custom Media Files via your script?
in the Broadworks docs i can see
UserAnnouncementFileLocationGetRequest
GroupAnnouncementFileLocationGetRequest
are within OCISchemaHidden.xsd

but dont see it within your models

thanks

**Comment by cwmiller** [comment]
I've added UserAnnouncementFileLocationGetRequest and GroupAnnouncementFileLocationGetRequest with version 3.1.4. When I tested these they would return an internal URL to the files, so I'm not sure how useful they are. I'm not really sure how to get a public URL to the files.

**Comment by TwinMist** [comment]
Nice work, many thanks just what i needed.
keep up the great work on this code.
