### ISSUE TITLE
Stir Shaken methods support

### ISSUE THREAD

**Issue by geyser7** [cwmiller/broadworks-connector#62]
Hello Chase,

Would it be possible to add Stir Shaken methods?

Specifically
OCISchemaServiceProvider.xsd:
- ServiceProviderStirShakenGetRequest
- ServiceProviderStirShakenGetResponse
- ServiceProviderStirShakenModifyRequest

OCISchemaGroup.xsd:
- GroupStirShakenGetRequest
- GroupStirShakenGetResponse
- GroupStirShakenModifyRequest
- GroupTrunkGroupStirShakenGetRequest
- GroupTrunkGroupStirShakenGetResponse
- GroupTrunkGroupStirShakenModifyRequest

Much appreciated

**Comment by cwmiller** [comment]
It looks like these were added as part of Release 24. The library right now is has everything up to and including Release 23. I'll work on getting the Release 24 models included, but I'm not sure how long it will take. It depends on how much has changed between the schemas for 23 and 24.

**Comment by TwinMist** [comment]
i am also running R24 so would great to update the schema
thanks

**Comment by geyser7** [comment]
Thank you Chase!

With Broadsoft's N-2 version support policy these were backported to R23 (probably R22 as well). I can see them in the last R23 xsds.
I am still running R23, it would be great if we can use these methods.
Thanks for all the good work!

**Comment by cwmiller** [comment]
Version 3.2.0 of the library was just published. It's built off R24's schema files and includes the STIR/SHAKEN methods.
