### ISSUE TITLE
Returned User Sequential Ring Location is always NULL

### ISSUE THREAD

**Issue by daraeman** [cwmiller/broadworks-connector#63]
I'm not sure if this is a problem on my end or the library's, but when I send a request to UserSequentialRingGetResponse14sp4 or UserSequentialRingGetRequest13mp16, the returned location params are always NULL. All the other params are returned and correct, just no the location ones.

The locations are confirmed set up for the user, and the location data is returned when I test via my own custom request, but not this library.

Additionally, setting the location data does work via UserSequentialRingModifyRequest, it is just still not returned when queried.

Example code:
Request:
```
$request = ( new \CWM\BroadWorksConnector\Ocip\Models\UserSequentialRingGetRequest14sp4() )
		->setUserId( $user_id );

$response = $ocip->UserSequentialRingGetRequest14sp4( $request );

var_dump( $response );
```
Response:
```
...
  ["Location01":"CWM\BroadWorksConnector\Ocip\Models\UserSequentialRingGetResponse14sp4":private]=>
  NULL
  ["Location02":"CWM\BroadWorksConnector\Ocip\Models\UserSequentialRingGetResponse14sp4":private]=>
  NULL
  ["Location03":"CWM\BroadWorksConnector\Ocip\Models\UserSequentialRingGetResponse14sp4":private]=>
  NULL
  ["Location04":"CWM\BroadWorksConnector\Ocip\Models\UserSequentialRingGetResponse14sp4":private]=>
  NULL
  ["Location05":"CWM\BroadWorksConnector\Ocip\Models\UserSequentialRingGetResponse14sp4":private]=>
  NULL
...
```

**Comment by cwmiller** [comment]
Thanks for reporting this. The issue was due to the library not expecting some properties to begin with an uppercase character. This is now fixed in release 3.2.2.
