### ISSUE TITLE
GroupOutgoingCallingPlanRedirectingModifyListRequest

### ISSUE THREAD

**Issue by andyrav** [cwmiller/broadworks-connector#8]
Hi 
Do you have a example how you would change the GroupOutgoingCallingPlanRedirecting. for a department

thanks

<command xsi:type="GroupOutgoingCallingPlanRedirectingModifyListRequest" xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <serviceProviderId>xxxxx</serviceProviderId>
    <groupId>xxxxx</groupId>
    <departmentPermissions>
      <departmentKey xsi:type="GroupDepartmentKey">
        <serviceProviderId>xxxxxL</serviceProviderId>
        <groupId>xxxxx</groupId>
        <name>Sales</name>
      </departmentKey>
      <permissions>
        <group>true</group>
        <local>false</local>
        <tollFree>false</tollFree>
        <toll>false</toll>
        <international>false</international>
        <operatorAssisted>true</operatorAssisted>
        <chargeableDirectoryAssisted>false</chargeableDirectoryAssisted>
        <specialServicesI>true</specialServicesI>
        <specialServicesII>false</specialServicesII>
        <premiumServicesI>false</premiumServicesI>
        <premiumServicesII>false</premiumServicesII>
        <casual>false</casual>
        <urlDialing>true</urlDialing>
        <unknown>true</unknown>
      </permissions>
    </departmentPermissions>

**Comment by cwmiller** [comment]
I did a test of `GroupOutgoingCallingPlanRedirectingModifyListRequest` and received an error response from the server. It looks like there's an issue with the handling of abstract classes, in this case the `DepartmentKey` class. I'm working on a fix.

**Comment by andyrav** [comment]
thanks for the fix, can you include a example how this should be coded?
cheers

**Comment by cwmiller** [comment]
What I was using to test:

```php
$departmentKey = (new GroupDepartmentKey())
    ->setServiceProviderId('Service Provider ID')
    ->setGroupId('Group ID')
    ->setName('Department Name');

$permissions = (new OutgoingCallingPlanRedirectingPermissionsModify())
    ->setGroup(true)
    ->setLocal(true)
    ->setTollFree(true)
    ->setToll(true)
    ->setInternational(false)
    ->setOperatorAssisted(false)
    ->setChargeableDirectoryAssisted(false)
    ->setSpecialServicesI(false)
    ->setSpecialServicesII(false)
    ->setPremiumServicesI(false)
    ->setPremiumServicesII(false)
    ->setCasual(false)
    ->setUrlDialing(false)
    ->setUnknown(false);

$departmentPermissions = (new OutgoingCallingPlanRedirectingDepartmentPermissionsModify())
    ->setDepartmentKey($departmentKey)
    ->setPermissions($permissions);

$request = (new GroupOutgoingCallingPlanRedirectingModifyListRequest())
    ->setServiceProviderId('Service Provider ID')
    ->setGroupId('Group ID')
    ->addDepartmentPermissions($departmentPermissions);

$response = $ocip->groupOutgoingCallingPlanRedirectingModifyListRequest($request);
```

**Comment by andyrav** [comment]
Hi, how would you include the groupPermissions into the same request
thanks

**Comment by cwmiller** [comment]
```php
$permissions = (new OutgoingCallingPlanRedirectingPermissionsModify())
    ->setGroup(true)
    ->setLocal(true)
    ->setTollFree(true)
    ->setToll(true)
    ->setInternational(false)
    ->setOperatorAssisted(false)
    ->setChargeableDirectoryAssisted(false)
    ->setSpecialServicesI(false)
    ->setSpecialServicesII(false)
    ->setPremiumServicesI(false)
    ->setPremiumServicesII(false)
    ->setCasual(false)
    ->setUrlDialing(false)
    ->setUnknown(false);

$request = (new GroupOutgoingCallingPlanRedirectingModifyListRequest())
    ->setServiceProviderId('Service Provider ID')
    ->setGroupId('Group ID')
    ->setGroupPermissions($permissions);

$response = $ocip->groupOutgoingCallingPlanRedirectingModifyListRequest($request);
