### ISSUE TITLE
example question

### ISSUE THREAD

**Issue by andyrav** [cwmiller/broadworks-connector#9]
Hi is your example on the front page correct?

try {
    $response = $ocip->userGetListInGroupRequest($request1);

should this be
try {
    $response = $ocip->call($request1);

as errors on your example
Uncaught Error: Call to undefined method CWM\BroadWorksConnector\OcipClient::UserGetListInGroupRequest() 
, but with call it returns the users with the group
thanks

**Comment by cwmiller** [comment]
The example is written for version 2. In v2, `call` is still available, but there's also helper methods for all the request types. These are intended to help when using an IDE that supports phpdoc, because the helper methods have @return annotations for each request type.
